### ISSUE TITLE
Laravel 4.2

### ISSUE THREAD

**Issue by axelphunter** [ollieread/multiauth#102]
For Laravel 4.2 version - links to Laravel 5 version
Thanks!

**Comment by ollieread** [comment]
There is no 4.2 version, only 4.1

**Comment by axelphunter** [comment]
Okay, no problem. My project was running off "dev-master" in my Laravel 4.2 project. Which version of multiauth should I now be using?

Thanks!

**Comment by ollieread** [comment]
I've updated dev-master, should now be 4.1 and 4.2 compat. Was an issue with merging that caused the initial L5 fiasco.

**Comment by axelphunter** [comment]
Great, thanks!
