### ISSUE TITLE
laravel 5.1 cannot worked 

### ISSUE THREAD

**Issue by apsana** [ollieread/multiauth#110]
add  config.php to providers Ollieread\Multiauth\MultiauthServiceProvider::class,  
error
Target [Illuminate\Contracts\Auth\Access\Gate] is not instantiable.

i look the file Illuminate\Contracts\Auth\Access\Gate is a interface

**Comment by ollieread** [comment]
This is something I'll be working on to fully update.

**Comment by unitedworx** [comment]
so this package work with 5.0 5.2 but does not work with 5.1 which is an LTS version?

**Comment by ollieread** [comment]
@unitedworx This project has actually been discontinued. The functionality was brought into 5.2 if memory serves.
