### ISSUE TITLE
What do I have to do to change the name of Account to User?

### ISSUE THREAD

**Issue by kazi-mainuddin-ahmed** [ollieread/multiauth#111]
How do I change the auth group name Account to User?
Is it possible? If so then Tell me how to do it with your code.

I have reviewed all your code files... But the word 'account' nowhere seems to exist.
Does that mean it will work with whatever we name it in the auth.php file?

**Comment by ollieread** [comment]
As the documentation states, the method account as in `Auth::account()` is based on the name in the configuration.
