### ISSUE TITLE
Target [Illuminate\Contracts\Auth\UserProvider] is not instantiable.

### ISSUE THREAD

**Issue by kazi-mainuddin-ahmed** [ollieread/multiauth#112]
My Routes:
```php
Route::group(['prefix' => 'catalyst-wcms', 'namespace' => 'Backend', 'middleware' => 'auth'], function(){
    Route::get('/', ['as' => 'dashboard', 'uses' => 'BackendController@index']);
});
```

Included `use Ollieread\Multiauth\Guard;` in `Authenticate.php` i.e. `auth` middleware

This code was just working before I installed multiauth.

I have installed `dev-laravel5` version by the way.

**Comment by ollieread** [comment]
This package as is, doesn't work with Laravel 5.1. That's actually something I'm working on.
