### ISSUE TITLE
intregreting with zizaco entrust permission

### ISSUE THREAD

**Issue by saurovh** [ollieread/multiauth#50]
hi, thanks for you library. i am using laravel default auth and entrust permission together. but some how i needed multiauth now so i implemented it. its works. but before i was checking permission like this .. Entrust::->can(); .. not how should i implement it ?

**Comment by faradoxuz** [comment]
Auth::user()->get()->hasRole('Admin') not working. 
Call to undefined method Illuminate\Auth\GenericUser::hasRole()
