### ISSUE TITLE
How to include thirdparty auth

### ISSUE THREAD

**Issue by syphernl** [ollieread/multiauth#66]
I'd like to use one of the available LDAP packages for Laravel to add support. 
However, I have tried a few but all of them are not working and resulting in an exception:

```
Driver [ldap] not supported. 
```

I have tried to replace the Guard in their vendor files with yours but this doesn't work either. Any suggestions on how to get this to work?

I have tried:
- https://github.com/ccovey/ldap-auth
- https://github.com/yuri-moens/l4-openldap
- https://github.com/dsdevbe/ldap-connector
- https://github.com/atorscho/laravel-ldap-42

But all of them end up with the same pesky error. Some packages (except for the ones listed) require replacement of the Auth provider which obviously wouldn't work. But those that simply add an additional one should right?

**Comment by jasonspick** [comment]
I'm having the same issue, I am working with strebl/l5-ldap-auth and I'm not sure how or were I extend it. is there any documentation on this?

**Comment by ollieread** [comment]
The documentation for this can be found on the laravel documentation, this package simply extends `Auth` slightly, where before you would do `Auth::extend()` now you do `Auth::admin()->extend()`.
