### ISSUE TITLE
How to get Eloquent user() object? From Auth::user()

### ISSUE THREAD

**Issue by rajanrawal** [ollieread/multiauth#67]
With Auth::user()->get() I am able to get the properties of the User Class but I am not able to access the relationships, obvious thing is that it returns me a Illuminate\Auth\GenericUser class. What is I want to get a User Class ( The main model ) Object? As because I want to access the other functions of User model, mostly relationships

**Comment by pdcmoreira** [comment]
So, how to solve this?
I'm trying to:
```php
$document->creator()->associate(Auth::user()->get());
```
Output:
```
Argument 1 passed to Illuminate\Database\Eloquent\Relations\BelongsTo::associate() must be an instance of Illuminate\Database\Eloquent\Model, instance of Illuminate\Auth\GenericUser given, called in  (...)
```
