### ISSUE TITLE
Problems on logout

### ISSUE THREAD

**Issue by jammersonf** [ollieread/multiauth#73]
I'm having trouble logout user.

I try to use Auth::logout(); or Auth::coach()->logout().  it passes through the code but still logged User

(Sorry for bad english)

**Comment by chhumsina** [comment]
Hi @jammersonf 
I have faced this problem. Could you guide me this tip?
Thanks you.

**Comment by jammersonf** [comment]
I don't remember what was happening exactly, this way is solved. Also check the routes and filters.

```php
public function getLogout()
{
	Auth::coach()->logout();
	Auth::user()->logout();
	Session::flush();
	return Redirect::to('/login');
}
```

**Comment by chhumsina** [comment]
Thanks you so much :)
