### ISSUE TITLE
Auth check() not working? after attempt It always returns true

### ISSUE THREAD

**Issue by msonowal** [ollieread/multiauth#79]
My Login Function Implementation
On AdminController()

    public function doLogin()
    {
        $remember = (Input::has('remember_me')) ? true : false;
        Auth::admin()->attempt(array(
            'username' => Input::get('username'),
             'password' => Input::get('password')
        ), $remember);

        if(Auth::admin()->check()) {
            return Redirect::intended('/'); //It is always returning true so it is redirecting 
        } else {
            return Redirect::back()->withErrors(['Either Username or Password is Incorrect!']);*/
        }
    }

and This is my filter

    Route::filter('auth.admin', function()
    {	
        (Auth::admin()->guest())
        return View::make('admins.login')->with('message', 'Please login using your credentials');*/
    });

Please fix my issue I love your plugin because of multi table based authentication but I am stuckked while implementing. PLease help

**Comment by ollieread** [comment]
I think your filter code is broke, why are you checking for `guest()`?

**Comment by msonowal** [comment]
by the way thanks for the late reply, YOur plugin really helped me and I fixed that out
One more issue was password reset
CAn please fix it or upload a example of using password reset on multi auth thank you

**Comment by ollieread** [comment]
Password reset isn't broken, and I can't suggest anything if you don't tell me what's wrong.

**Comment by msonowal** [comment]
OK If it's well then can you show me or link me to some examples
of Password reset Controller route and the view , please
thanks in advance..

**Comment by InfiniteDevelopment** [comment]
I can confirm this does not work... Unable to use ->check()

**Comment by ollieread** [comment]
Check always returns true? Also, what version, this package and laravel.
