### ISSUE TITLE
Multiauth is will not work on Laravel 5.0?

### ISSUE THREAD

**Issue by JoshuaSarav** [ollieread/multiauth#82]
Hi, I have been using your multiauth in laravel 4.2. It works great. But I'm unable to install it in laravel 5.0(I tried installing it via composer). Any update for laravel 5.0?

**Comment by mul14** [comment]
Not yet. But you can fork and send pull request.

**Comment by jithujose** [comment]
@mul14 Do you've any intention to port it anytime soon to Laravel 5.0?

**Comment by ollieread** [comment]
@jithujose  I honestly haven't had chance to update this for Laravel 5.0 as I've had a lot of work on, as well as some other larger personal projects. As @mul14 said, I'm open to pull requests.
