### ISSUE TITLE
Any alternative solution for Auth::viaRemember()?

### ISSUE THREAD

**Issue by rajanrawal** [ollieread/multiauth#84]
Hi, Writhing this to know if any alternative to detect user coming viaRememner. Package is best known to you. So just asked.

**Comment by ollieread** [comment]
It'd be the same way as it would normally `Auth::yourAuthType()->viaRemember()`.

**Comment by rajanrawal** [comment]
Oh! Damn easy! Sorry I did not even try it. Thanks!

On Thu, Feb 26, 2015 at 11:49 PM, Ollie Read <notifications@github.com>
wrote:

> It'd be the same way as it would normally
> Auth::yourAuthType()->viaRemember().
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ollieread/multiauth/issues/84#issuecomment-76234080>.
>



-- 
Thank You & Regards,
Rajan Y. Rawal
+91 897 608 4840* | *rajan.rwl@gmail.com
