### ISSUE TITLE
How do I know Which Auth::<usertype>() is logged in? I need to do run time check, Actually I want to user in "auth.login" events

### ISSUE THREAD

**Issue by rajanrawal** [ollieread/multiauth#85]
Of course we can use if condition as many multiauth we want. But is there any method by which can we can find current type from different multiauth. How can I find it? As I said I want to use it in Laravel "auth.login" event, I tired "auth.admin.login" but not there. So want to do other way round. Thanks!

**Comment by ollieread** [comment]
Create yourself an auth.admin.login event?
