### ISSUE TITLE
Entrust::can('') not working

### ISSUE THREAD

**Issue by chhumsina** [ollieread/multiauth#88]
Hi,

It works well with multiple authentication but i have problem with Entrust::can(''). 
Do any tip for that or any recommend?

Thanks you :)

**Comment by ollieread** [comment]
Afaik, Entrust is designed to work with default Auth, so I wouldn't be able to suggest anything, plus I've never used Entrust myself.

**Comment by chhumsina** [comment]
Thanks you :)
