### ISSUE TITLE
Password reminder

### ISSUE THREAD

**Issue by ThunderPaul** [ollieread/multiauth#96]
Hello,
I did not understand how to reset the password.

From what I have read before you will receive an email with a link to reset the password, once you click on the link as I have to create the controller to reset?

You can not send the password reset it?

Thank you.

**Comment by terdelyi** [comment]
Yes, you have. Everything is described in Laravel docs and working as the same in multiauth: http://laravel.com/docs/4.2/security#password-reminders-and-reset

> Your user will receive an e-mail with a link that points to the getReset method of the controller. The password reminder token, which is used to identify a given password reminder attempt, will also be passed to the controller method. The action is already configured to return a password.reset view which you should build. The token will be passed to the view, and you should place this token in a hidden form field named token. In addition to the token, your password reset form should contain email, password, and password_confirmation fields. The form should POST to the RemindersController@postReset method.

**Comment by ollieread** [comment]
Yes, it works the same as the default Laravel provider for reminders, except you obviously need to make a few amendments to cater for this. All information is included in the initial readme.
