### ISSUE TITLE
Dynamic users N

### ISSUE THREAD

**Issue by achucuan** [ollieread/multiauth#99]
Library works great but I need a way to have multi sessions dynamicly so I can use as many user sessions as they are needed

At the moment as I understand your library as I understand supports as many sessions as they are configured in config.auth

```
'multi' => array(
        'account' => array(
            'driver' => 'database',
            'table' => 'users'
        ),
        'user' => array(
            'driver' => 'database',
            'table' => 'users'
        )
    ),
```

If there's a way to do this It would be awesome

**Comment by ollieread** [comment]
I'm afraid I do not follow. Do you mean that you need a user to be logged in as two or more kinds of users, at any one time? If so, there's no technical reason on my side why that wouldn't be possible.
